import Handlebars from 'handlebars';
import analytics from '../helpers/analytics.js';
import bodyClass from '../helpers/bodyClass.js';
import debug from '../helpers/debug.js';
import featuredImg from '../helpers/featuredImg.js';
import getRelatedPosts from '../helpers/getRelatedPosts.js';
import getThumb from '../helpers/getThumb.js';
import pageDescription from '../helpers/pageDescription.js';
import pageTitle from '../helpers/pageTitle.js';
import setExtScripts from '../helpers/setExtScripts.js';
import setJS from '../helpers/setJS.js';
import setScripts from '../helpers/setScripts.js';
import setURL from '../helpers/setURL.js';
import setVideos from '../helpers/setVideos.js';
import siteNav from '../helpers/siteNav.js';

export default (files, metalsmith, done) => {
  setImmediate(done);
  Handlebars.registerHelper('analytics', analytics);
  Handlebars.registerHelper('bodyClass', bodyClass);
  Handlebars.registerHelper('debug', debug);
  Handlebars.registerHelper('featuredImg', featuredImg);
  Handlebars.registerHelper('getRelatedPosts', getRelatedPosts);
  Handlebars.registerHelper('getThumb', getThumb);
  Handlebars.registerHelper('pageDescription', pageDescription);
  Handlebars.registerHelper('pageTitle', pageTitle);
  Handlebars.registerHelper('setExtScripts', setExtScripts);
  Handlebars.registerHelper('setJS', setJS);
  Handlebars.registerHelper('setScripts', setScripts);
  Handlebars.registerHelper('setURL', setURL);
  Handlebars.registerHelper('setVideos', setVideos);
  Handlebars.registerHelper('siteNav', siteNav);
};
